export const ACTION_SEEK = "ACTION_SEEK";
export const ACTION_SELECT_PART = "ACTION_SELECT_PART";
export const ACTION_AUTO_SEEK = "ACTION_AUTO_SEEK";
export const ACTION_SET_LOADING = "ACTION_SET_LOADING";
export const ACTION_LOAD_ROUTES = "ACTION_LOAD_ROUTES";
export const ACTION_SELECT_ROUTE = "ACTION_SELECT_ROUTE";
export const ACTION_SET_MAX_TIME = "ACTION_SET_MAX_TIME";
export const ACTION_SELECT_SEGMENT = "ACTION_SELECT_SEGMENT";
