export const ACTION_SEEK = "ACTION_SEEK";
export const ACTION_SELECT_PART = "ACTION_SELECT_PART";
export const ACTION_AUTO_SEEK = "ACTION_AUTO_SEEK";
export const ACTION_SET_LOADING = "ACTION_SET_LOADING";
export const ACTION_SELECT_ROUTE = "ACTION_SELECT_ROUTE";
